// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_contacts_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_contacts_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_contacts_2eproto;
namespace contacts {
class Address;
struct AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
class Contacts;
struct ContactsDefaultTypeInternal;
extern ContactsDefaultTypeInternal _Contacts_default_instance_;
class People;
struct PeopleDefaultTypeInternal;
extern PeopleDefaultTypeInternal _People_default_instance_;
class People_RemarkEntry_DoNotUse;
struct People_RemarkEntry_DoNotUseDefaultTypeInternal;
extern People_RemarkEntry_DoNotUseDefaultTypeInternal _People_RemarkEntry_DoNotUse_default_instance_;
class Phone;
struct PhoneDefaultTypeInternal;
extern PhoneDefaultTypeInternal _Phone_default_instance_;
}  // namespace contacts
PROTOBUF_NAMESPACE_OPEN
template<> ::contacts::Address* Arena::CreateMaybeMessage<::contacts::Address>(Arena*);
template<> ::contacts::Contacts* Arena::CreateMaybeMessage<::contacts::Contacts>(Arena*);
template<> ::contacts::People* Arena::CreateMaybeMessage<::contacts::People>(Arena*);
template<> ::contacts::People_RemarkEntry_DoNotUse* Arena::CreateMaybeMessage<::contacts::People_RemarkEntry_DoNotUse>(Arena*);
template<> ::contacts::Phone* Arena::CreateMaybeMessage<::contacts::Phone>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace contacts {

enum PhoneType : int {
  UNKNOWN = 0,
  MOBILE_PHONE = 1,
  LANDLINE = 2,
  PhoneType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  PhoneType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool PhoneType_IsValid(int value);
constexpr PhoneType PhoneType_MIN = UNKNOWN;
constexpr PhoneType PhoneType_MAX = LANDLINE;
constexpr int PhoneType_ARRAYSIZE = PhoneType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PhoneType_descriptor();
template<typename T>
inline const std::string& PhoneType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PhoneType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PhoneType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PhoneType_descriptor(), enum_t_value);
}
inline bool PhoneType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PhoneType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PhoneType>(
    PhoneType_descriptor(), name, value);
}
// ===================================================================

class Address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Address) */ {
 public:
  inline Address() : Address(nullptr) {}
  ~Address() override;
  explicit PROTOBUF_CONSTEXPR Address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Address* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Address& from) {
    Address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Address";
  }
  protected:
  explicit Address(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHomeFieldNumber = 1,
    kWorkFieldNumber = 2,
  };
  // string home = 1;
  void clear_home();
  const std::string& home() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_home(ArgT0&& arg0, ArgT... args);
  std::string* mutable_home();
  PROTOBUF_NODISCARD std::string* release_home();
  void set_allocated_home(std::string* home);
  private:
  const std::string& _internal_home() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_home(const std::string& value);
  std::string* _internal_mutable_home();
  public:

  // string work = 2;
  void clear_work();
  const std::string& work() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_work(ArgT0&& arg0, ArgT... args);
  std::string* mutable_work();
  PROTOBUF_NODISCARD std::string* release_work();
  void set_allocated_work(std::string* work);
  private:
  const std::string& _internal_work() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_work(const std::string& value);
  std::string* _internal_mutable_work();
  public:

  // @@protoc_insertion_point(class_scope:contacts.Address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr home_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr work_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class Phone final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Phone) */ {
 public:
  inline Phone() : Phone(nullptr) {}
  ~Phone() override;
  explicit PROTOBUF_CONSTEXPR Phone(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Phone(const Phone& from);
  Phone(Phone&& from) noexcept
    : Phone() {
    *this = ::std::move(from);
  }

  inline Phone& operator=(const Phone& from) {
    CopyFrom(from);
    return *this;
  }
  inline Phone& operator=(Phone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Phone& default_instance() {
    return *internal_default_instance();
  }
  static inline const Phone* internal_default_instance() {
    return reinterpret_cast<const Phone*>(
               &_Phone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Phone& a, Phone& b) {
    a.Swap(&b);
  }
  inline void Swap(Phone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Phone* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Phone* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Phone>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Phone& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Phone& from) {
    Phone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Phone* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Phone";
  }
  protected:
  explicit Phone(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNumberFieldNumber = 1,
    kTypeFieldNumber = 2,
  };
  // string number = 1;
  void clear_number();
  const std::string& number() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_number(ArgT0&& arg0, ArgT... args);
  std::string* mutable_number();
  PROTOBUF_NODISCARD std::string* release_number();
  void set_allocated_number(std::string* number);
  private:
  const std::string& _internal_number() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_number(const std::string& value);
  std::string* _internal_mutable_number();
  public:

  // .contacts.PhoneType type = 2;
  void clear_type();
  ::contacts::PhoneType type() const;
  void set_type(::contacts::PhoneType value);
  private:
  ::contacts::PhoneType _internal_type() const;
  void _internal_set_type(::contacts::PhoneType value);
  public:

  // @@protoc_insertion_point(class_scope:contacts.Phone)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr number_;
    int type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class People_RemarkEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<People_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<People_RemarkEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  People_RemarkEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR People_RemarkEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit People_RemarkEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const People_RemarkEntry_DoNotUse& other);
  static const People_RemarkEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const People_RemarkEntry_DoNotUse*>(&_People_RemarkEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "contacts.People.RemarkEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "contacts.People.RemarkEntry.value");
 }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_contacts_2eproto;
};

// -------------------------------------------------------------------

class People final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.People) */ {
 public:
  inline People() : People(nullptr) {}
  ~People() override;
  explicit PROTOBUF_CONSTEXPR People(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  People(const People& from);
  People(People&& from) noexcept
    : People() {
    *this = ::std::move(from);
  }

  inline People& operator=(const People& from) {
    CopyFrom(from);
    return *this;
  }
  inline People& operator=(People&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const People& default_instance() {
    return *internal_default_instance();
  }
  enum OtherContactCase {
    kQq = 5,
    kWechat = 6,
    OTHER_CONTACT_NOT_SET = 0,
  };

  static inline const People* internal_default_instance() {
    return reinterpret_cast<const People*>(
               &_People_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(People& a, People& b) {
    a.Swap(&b);
  }
  inline void Swap(People* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(People* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  People* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<People>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const People& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const People& from) {
    People::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(People* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.People";
  }
  protected:
  explicit People(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kPhoneFieldNumber = 3,
    kRemarkFieldNumber = 7,
    kNameFieldNumber = 1,
    kDateFieldNumber = 4,
    kAgeFieldNumber = 2,
    kQqFieldNumber = 5,
    kWechatFieldNumber = 6,
  };
  // repeated .contacts.Phone phone = 3;
  int phone_size() const;
  private:
  int _internal_phone_size() const;
  public:
  void clear_phone();
  ::contacts::Phone* mutable_phone(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >*
      mutable_phone();
  private:
  const ::contacts::Phone& _internal_phone(int index) const;
  ::contacts::Phone* _internal_add_phone();
  public:
  const ::contacts::Phone& phone(int index) const;
  ::contacts::Phone* add_phone();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >&
      phone() const;

  // map<string, string> remark = 7;
  int remark_size() const;
  private:
  int _internal_remark_size() const;
  public:
  void clear_remark();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_remark();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      remark() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_remark();

  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // .google.protobuf.Any date = 4;
  bool has_date() const;
  private:
  bool _internal_has_date() const;
  public:
  void clear_date();
  const ::PROTOBUF_NAMESPACE_ID::Any& date() const;
  PROTOBUF_NODISCARD ::PROTOBUF_NAMESPACE_ID::Any* release_date();
  ::PROTOBUF_NAMESPACE_ID::Any* mutable_date();
  void set_allocated_date(::PROTOBUF_NAMESPACE_ID::Any* date);
  private:
  const ::PROTOBUF_NAMESPACE_ID::Any& _internal_date() const;
  ::PROTOBUF_NAMESPACE_ID::Any* _internal_mutable_date();
  public:
  void unsafe_arena_set_allocated_date(
      ::PROTOBUF_NAMESPACE_ID::Any* date);
  ::PROTOBUF_NAMESPACE_ID::Any* unsafe_arena_release_date();

  // int32 age = 2;
  void clear_age();
  int32_t age() const;
  void set_age(int32_t value);
  private:
  int32_t _internal_age() const;
  void _internal_set_age(int32_t value);
  public:

  // string qq = 5;
  bool has_qq() const;
  private:
  bool _internal_has_qq() const;
  public:
  void clear_qq();
  const std::string& qq() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_qq(ArgT0&& arg0, ArgT... args);
  std::string* mutable_qq();
  PROTOBUF_NODISCARD std::string* release_qq();
  void set_allocated_qq(std::string* qq);
  private:
  const std::string& _internal_qq() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_qq(const std::string& value);
  std::string* _internal_mutable_qq();
  public:

  // string wechat = 6;
  bool has_wechat() const;
  private:
  bool _internal_has_wechat() const;
  public:
  void clear_wechat();
  const std::string& wechat() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_wechat(ArgT0&& arg0, ArgT... args);
  std::string* mutable_wechat();
  PROTOBUF_NODISCARD std::string* release_wechat();
  void set_allocated_wechat(std::string* wechat);
  private:
  const std::string& _internal_wechat() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_wechat(const std::string& value);
  std::string* _internal_mutable_wechat();
  public:

  void clear_other_contact();
  OtherContactCase other_contact_case() const;
  // @@protoc_insertion_point(class_scope:contacts.People)
 private:
  class _Internal;
  void set_has_qq();
  void set_has_wechat();

  inline bool has_other_contact() const;
  inline void clear_has_other_contact();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone > phone_;
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        People_RemarkEntry_DoNotUse,
        std::string, std::string,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> remark_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::Any* date_;
    int32_t age_;
    union OtherContactUnion {
      constexpr OtherContactUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr qq_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr wechat_;
    } other_contact_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// -------------------------------------------------------------------

class Contacts final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:contacts.Contacts) */ {
 public:
  inline Contacts() : Contacts(nullptr) {}
  ~Contacts() override;
  explicit PROTOBUF_CONSTEXPR Contacts(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Contacts(const Contacts& from);
  Contacts(Contacts&& from) noexcept
    : Contacts() {
    *this = ::std::move(from);
  }

  inline Contacts& operator=(const Contacts& from) {
    CopyFrom(from);
    return *this;
  }
  inline Contacts& operator=(Contacts&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Contacts& default_instance() {
    return *internal_default_instance();
  }
  static inline const Contacts* internal_default_instance() {
    return reinterpret_cast<const Contacts*>(
               &_Contacts_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Contacts& a, Contacts& b) {
    a.Swap(&b);
  }
  inline void Swap(Contacts* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Contacts* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Contacts* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Contacts>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Contacts& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Contacts& from) {
    Contacts::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Contacts* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "contacts.Contacts";
  }
  protected:
  explicit Contacts(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPeopleFieldNumber = 1,
  };
  // repeated .contacts.People people = 1;
  int people_size() const;
  private:
  int _internal_people_size() const;
  public:
  void clear_people();
  ::contacts::People* mutable_people(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::People >*
      mutable_people();
  private:
  const ::contacts::People& _internal_people(int index) const;
  ::contacts::People* _internal_add_people();
  public:
  const ::contacts::People& people(int index) const;
  ::contacts::People* add_people();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::People >&
      people() const;

  // @@protoc_insertion_point(class_scope:contacts.Contacts)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::People > people_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_contacts_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Address

// string home = 1;
inline void Address::clear_home() {
  _impl_.home_.ClearToEmpty();
}
inline const std::string& Address::home() const {
  // @@protoc_insertion_point(field_get:contacts.Address.home)
  return _internal_home();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_home(ArgT0&& arg0, ArgT... args) {
 
 _impl_.home_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Address.home)
}
inline std::string* Address::mutable_home() {
  std::string* _s = _internal_mutable_home();
  // @@protoc_insertion_point(field_mutable:contacts.Address.home)
  return _s;
}
inline const std::string& Address::_internal_home() const {
  return _impl_.home_.Get();
}
inline void Address::_internal_set_home(const std::string& value) {
  
  _impl_.home_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_home() {
  
  return _impl_.home_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_home() {
  // @@protoc_insertion_point(field_release:contacts.Address.home)
  return _impl_.home_.Release();
}
inline void Address::set_allocated_home(std::string* home) {
  if (home != nullptr) {
    
  } else {
    
  }
  _impl_.home_.SetAllocated(home, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.home_.IsDefault()) {
    _impl_.home_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Address.home)
}

// string work = 2;
inline void Address::clear_work() {
  _impl_.work_.ClearToEmpty();
}
inline const std::string& Address::work() const {
  // @@protoc_insertion_point(field_get:contacts.Address.work)
  return _internal_work();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Address::set_work(ArgT0&& arg0, ArgT... args) {
 
 _impl_.work_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Address.work)
}
inline std::string* Address::mutable_work() {
  std::string* _s = _internal_mutable_work();
  // @@protoc_insertion_point(field_mutable:contacts.Address.work)
  return _s;
}
inline const std::string& Address::_internal_work() const {
  return _impl_.work_.Get();
}
inline void Address::_internal_set_work(const std::string& value) {
  
  _impl_.work_.Set(value, GetArenaForAllocation());
}
inline std::string* Address::_internal_mutable_work() {
  
  return _impl_.work_.Mutable(GetArenaForAllocation());
}
inline std::string* Address::release_work() {
  // @@protoc_insertion_point(field_release:contacts.Address.work)
  return _impl_.work_.Release();
}
inline void Address::set_allocated_work(std::string* work) {
  if (work != nullptr) {
    
  } else {
    
  }
  _impl_.work_.SetAllocated(work, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.work_.IsDefault()) {
    _impl_.work_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Address.work)
}

// -------------------------------------------------------------------

// Phone

// string number = 1;
inline void Phone::clear_number() {
  _impl_.number_.ClearToEmpty();
}
inline const std::string& Phone::number() const {
  // @@protoc_insertion_point(field_get:contacts.Phone.number)
  return _internal_number();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Phone::set_number(ArgT0&& arg0, ArgT... args) {
 
 _impl_.number_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.Phone.number)
}
inline std::string* Phone::mutable_number() {
  std::string* _s = _internal_mutable_number();
  // @@protoc_insertion_point(field_mutable:contacts.Phone.number)
  return _s;
}
inline const std::string& Phone::_internal_number() const {
  return _impl_.number_.Get();
}
inline void Phone::_internal_set_number(const std::string& value) {
  
  _impl_.number_.Set(value, GetArenaForAllocation());
}
inline std::string* Phone::_internal_mutable_number() {
  
  return _impl_.number_.Mutable(GetArenaForAllocation());
}
inline std::string* Phone::release_number() {
  // @@protoc_insertion_point(field_release:contacts.Phone.number)
  return _impl_.number_.Release();
}
inline void Phone::set_allocated_number(std::string* number) {
  if (number != nullptr) {
    
  } else {
    
  }
  _impl_.number_.SetAllocated(number, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.number_.IsDefault()) {
    _impl_.number_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.Phone.number)
}

// .contacts.PhoneType type = 2;
inline void Phone::clear_type() {
  _impl_.type_ = 0;
}
inline ::contacts::PhoneType Phone::_internal_type() const {
  return static_cast< ::contacts::PhoneType >(_impl_.type_);
}
inline ::contacts::PhoneType Phone::type() const {
  // @@protoc_insertion_point(field_get:contacts.Phone.type)
  return _internal_type();
}
inline void Phone::_internal_set_type(::contacts::PhoneType value) {
  
  _impl_.type_ = value;
}
inline void Phone::set_type(::contacts::PhoneType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:contacts.Phone.type)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// People

// string name = 1;
inline void People::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& People::name() const {
  // @@protoc_insertion_point(field_get:contacts.People.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void People::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.People.name)
}
inline std::string* People::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:contacts.People.name)
  return _s;
}
inline const std::string& People::_internal_name() const {
  return _impl_.name_.Get();
}
inline void People::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* People::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* People::release_name() {
  // @@protoc_insertion_point(field_release:contacts.People.name)
  return _impl_.name_.Release();
}
inline void People::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:contacts.People.name)
}

// int32 age = 2;
inline void People::clear_age() {
  _impl_.age_ = 0;
}
inline int32_t People::_internal_age() const {
  return _impl_.age_;
}
inline int32_t People::age() const {
  // @@protoc_insertion_point(field_get:contacts.People.age)
  return _internal_age();
}
inline void People::_internal_set_age(int32_t value) {
  
  _impl_.age_ = value;
}
inline void People::set_age(int32_t value) {
  _internal_set_age(value);
  // @@protoc_insertion_point(field_set:contacts.People.age)
}

// repeated .contacts.Phone phone = 3;
inline int People::_internal_phone_size() const {
  return _impl_.phone_.size();
}
inline int People::phone_size() const {
  return _internal_phone_size();
}
inline void People::clear_phone() {
  _impl_.phone_.Clear();
}
inline ::contacts::Phone* People::mutable_phone(int index) {
  // @@protoc_insertion_point(field_mutable:contacts.People.phone)
  return _impl_.phone_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >*
People::mutable_phone() {
  // @@protoc_insertion_point(field_mutable_list:contacts.People.phone)
  return &_impl_.phone_;
}
inline const ::contacts::Phone& People::_internal_phone(int index) const {
  return _impl_.phone_.Get(index);
}
inline const ::contacts::Phone& People::phone(int index) const {
  // @@protoc_insertion_point(field_get:contacts.People.phone)
  return _internal_phone(index);
}
inline ::contacts::Phone* People::_internal_add_phone() {
  return _impl_.phone_.Add();
}
inline ::contacts::Phone* People::add_phone() {
  ::contacts::Phone* _add = _internal_add_phone();
  // @@protoc_insertion_point(field_add:contacts.People.phone)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::Phone >&
People::phone() const {
  // @@protoc_insertion_point(field_list:contacts.People.phone)
  return _impl_.phone_;
}

// .google.protobuf.Any date = 4;
inline bool People::_internal_has_date() const {
  return this != internal_default_instance() && _impl_.date_ != nullptr;
}
inline bool People::has_date() const {
  return _internal_has_date();
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& People::_internal_date() const {
  const ::PROTOBUF_NAMESPACE_ID::Any* p = _impl_.date_;
  return p != nullptr ? *p : reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Any&>(
      ::PROTOBUF_NAMESPACE_ID::_Any_default_instance_);
}
inline const ::PROTOBUF_NAMESPACE_ID::Any& People::date() const {
  // @@protoc_insertion_point(field_get:contacts.People.date)
  return _internal_date();
}
inline void People::unsafe_arena_set_allocated_date(
    ::PROTOBUF_NAMESPACE_ID::Any* date) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.date_);
  }
  _impl_.date_ = date;
  if (date) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:contacts.People.date)
}
inline ::PROTOBUF_NAMESPACE_ID::Any* People::release_date() {
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.date_;
  _impl_.date_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* People::unsafe_arena_release_date() {
  // @@protoc_insertion_point(field_release:contacts.People.date)
  
  ::PROTOBUF_NAMESPACE_ID::Any* temp = _impl_.date_;
  _impl_.date_ = nullptr;
  return temp;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* People::_internal_mutable_date() {
  
  if (_impl_.date_ == nullptr) {
    auto* p = CreateMaybeMessage<::PROTOBUF_NAMESPACE_ID::Any>(GetArenaForAllocation());
    _impl_.date_ = p;
  }
  return _impl_.date_;
}
inline ::PROTOBUF_NAMESPACE_ID::Any* People::mutable_date() {
  ::PROTOBUF_NAMESPACE_ID::Any* _msg = _internal_mutable_date();
  // @@protoc_insertion_point(field_mutable:contacts.People.date)
  return _msg;
}
inline void People::set_allocated_date(::PROTOBUF_NAMESPACE_ID::Any* date) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.date_);
  }
  if (date) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(date));
    if (message_arena != submessage_arena) {
      date = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, date, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.date_ = date;
  // @@protoc_insertion_point(field_set_allocated:contacts.People.date)
}

// string qq = 5;
inline bool People::_internal_has_qq() const {
  return other_contact_case() == kQq;
}
inline bool People::has_qq() const {
  return _internal_has_qq();
}
inline void People::set_has_qq() {
  _impl_._oneof_case_[0] = kQq;
}
inline void People::clear_qq() {
  if (_internal_has_qq()) {
    _impl_.other_contact_.qq_.Destroy();
    clear_has_other_contact();
  }
}
inline const std::string& People::qq() const {
  // @@protoc_insertion_point(field_get:contacts.People.qq)
  return _internal_qq();
}
template <typename ArgT0, typename... ArgT>
inline void People::set_qq(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  _impl_.other_contact_.qq_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.People.qq)
}
inline std::string* People::mutable_qq() {
  std::string* _s = _internal_mutable_qq();
  // @@protoc_insertion_point(field_mutable:contacts.People.qq)
  return _s;
}
inline const std::string& People::_internal_qq() const {
  if (_internal_has_qq()) {
    return _impl_.other_contact_.qq_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void People::_internal_set_qq(const std::string& value) {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  _impl_.other_contact_.qq_.Set(value, GetArenaForAllocation());
}
inline std::string* People::_internal_mutable_qq() {
  if (!_internal_has_qq()) {
    clear_other_contact();
    set_has_qq();
    _impl_.other_contact_.qq_.InitDefault();
  }
  return _impl_.other_contact_.qq_.Mutable(      GetArenaForAllocation());
}
inline std::string* People::release_qq() {
  // @@protoc_insertion_point(field_release:contacts.People.qq)
  if (_internal_has_qq()) {
    clear_has_other_contact();
    return _impl_.other_contact_.qq_.Release();
  } else {
    return nullptr;
  }
}
inline void People::set_allocated_qq(std::string* qq) {
  if (has_other_contact()) {
    clear_other_contact();
  }
  if (qq != nullptr) {
    set_has_qq();
    _impl_.other_contact_.qq_.InitAllocated(qq, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.People.qq)
}

// string wechat = 6;
inline bool People::_internal_has_wechat() const {
  return other_contact_case() == kWechat;
}
inline bool People::has_wechat() const {
  return _internal_has_wechat();
}
inline void People::set_has_wechat() {
  _impl_._oneof_case_[0] = kWechat;
}
inline void People::clear_wechat() {
  if (_internal_has_wechat()) {
    _impl_.other_contact_.wechat_.Destroy();
    clear_has_other_contact();
  }
}
inline const std::string& People::wechat() const {
  // @@protoc_insertion_point(field_get:contacts.People.wechat)
  return _internal_wechat();
}
template <typename ArgT0, typename... ArgT>
inline void People::set_wechat(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  _impl_.other_contact_.wechat_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:contacts.People.wechat)
}
inline std::string* People::mutable_wechat() {
  std::string* _s = _internal_mutable_wechat();
  // @@protoc_insertion_point(field_mutable:contacts.People.wechat)
  return _s;
}
inline const std::string& People::_internal_wechat() const {
  if (_internal_has_wechat()) {
    return _impl_.other_contact_.wechat_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void People::_internal_set_wechat(const std::string& value) {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  _impl_.other_contact_.wechat_.Set(value, GetArenaForAllocation());
}
inline std::string* People::_internal_mutable_wechat() {
  if (!_internal_has_wechat()) {
    clear_other_contact();
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitDefault();
  }
  return _impl_.other_contact_.wechat_.Mutable(      GetArenaForAllocation());
}
inline std::string* People::release_wechat() {
  // @@protoc_insertion_point(field_release:contacts.People.wechat)
  if (_internal_has_wechat()) {
    clear_has_other_contact();
    return _impl_.other_contact_.wechat_.Release();
  } else {
    return nullptr;
  }
}
inline void People::set_allocated_wechat(std::string* wechat) {
  if (has_other_contact()) {
    clear_other_contact();
  }
  if (wechat != nullptr) {
    set_has_wechat();
    _impl_.other_contact_.wechat_.InitAllocated(wechat, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:contacts.People.wechat)
}

// map<string, string> remark = 7;
inline int People::_internal_remark_size() const {
  return _impl_.remark_.size();
}
inline int People::remark_size() const {
  return _internal_remark_size();
}
inline void People::clear_remark() {
  _impl_.remark_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
People::_internal_remark() const {
  return _impl_.remark_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
People::remark() const {
  // @@protoc_insertion_point(field_map:contacts.People.remark)
  return _internal_remark();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
People::_internal_mutable_remark() {
  return _impl_.remark_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
People::mutable_remark() {
  // @@protoc_insertion_point(field_mutable_map:contacts.People.remark)
  return _internal_mutable_remark();
}

inline bool People::has_other_contact() const {
  return other_contact_case() != OTHER_CONTACT_NOT_SET;
}
inline void People::clear_has_other_contact() {
  _impl_._oneof_case_[0] = OTHER_CONTACT_NOT_SET;
}
inline People::OtherContactCase People::other_contact_case() const {
  return People::OtherContactCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Contacts

// repeated .contacts.People people = 1;
inline int Contacts::_internal_people_size() const {
  return _impl_.people_.size();
}
inline int Contacts::people_size() const {
  return _internal_people_size();
}
inline void Contacts::clear_people() {
  _impl_.people_.Clear();
}
inline ::contacts::People* Contacts::mutable_people(int index) {
  // @@protoc_insertion_point(field_mutable:contacts.Contacts.people)
  return _impl_.people_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::People >*
Contacts::mutable_people() {
  // @@protoc_insertion_point(field_mutable_list:contacts.Contacts.people)
  return &_impl_.people_;
}
inline const ::contacts::People& Contacts::_internal_people(int index) const {
  return _impl_.people_.Get(index);
}
inline const ::contacts::People& Contacts::people(int index) const {
  // @@protoc_insertion_point(field_get:contacts.Contacts.people)
  return _internal_people(index);
}
inline ::contacts::People* Contacts::_internal_add_people() {
  return _impl_.people_.Add();
}
inline ::contacts::People* Contacts::add_people() {
  ::contacts::People* _add = _internal_add_people();
  // @@protoc_insertion_point(field_add:contacts.Contacts.people)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::contacts::People >&
Contacts::people() const {
  // @@protoc_insertion_point(field_list:contacts.Contacts.people)
  return _impl_.people_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace contacts

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::contacts::PhoneType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::contacts::PhoneType>() {
  return ::contacts::PhoneType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_contacts_2eproto
