// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: testenum2.proto

#include "testenum2.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace testenum2 {
}  // namespace testenum2
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_testenum2_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_testenum2_2eproto = nullptr;
const uint32_t TableStruct_testenum2_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_testenum2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017testenum2.proto\022\ttestenum2\032\016testenum.p"
  "roto*\r\n\002ss\022\007\n\003MAN\020\000b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_testenum2_2eproto_deps[1] = {
  &::descriptor_table_testenum_2eproto,
};
static ::_pbi::once_flag descriptor_table_testenum2_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_testenum2_2eproto = {
    false, false, 67, descriptor_table_protodef_testenum2_2eproto,
    "testenum2.proto",
    &descriptor_table_testenum2_2eproto_once, descriptor_table_testenum2_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_testenum2_2eproto::offsets,
    nullptr, file_level_enum_descriptors_testenum2_2eproto,
    file_level_service_descriptors_testenum2_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_testenum2_2eproto_getter() {
  return &descriptor_table_testenum2_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_testenum2_2eproto(&descriptor_table_testenum2_2eproto);
namespace testenum2 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ss_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_testenum2_2eproto);
  return file_level_enum_descriptors_testenum2_2eproto[0];
}
bool ss_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace testenum2
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
